### PR TITLE
Factor out HIV1B-specific code in the CLI interface

### PR DESCRIPTION
**Pull request by neganp**
These commits factor HIV1B specific code in the CLI package into a separate package. This is almost 100% moving code around, with a few new data types to make passing information from the genome-specific alignment procedure into the generic alignment procedure less verbose.

### CODE REVIEW

**Comment by philiptzou** [comment]
It looks like you did something I planned to do for a long time. Just give me a few days to review the code and I'll merge it.

Thanks!

**Comment by neganp** [comment]
Cool! 😊

I hope it's not too far from what you intended. I'm happy to make changes
if it would make the PR for better with the rest of the project.

**Comment by philiptzou** [comment]
@neganp My original intention was to make a general command which can accept an alignment profile file (probably in YAML format) which includes the reference, gap penalty scores, positional indel bonus/penalty scores.

I just have a quick look of your approach. I think it is getting closer to my original thoughts and we can definitely develop the profile file support based on your version.

I'd also like to make a few changes to the subcommands. We will have some built-in profiles like HIV1B and HCV1A. However, it will not be subcommands in the future version. Here's my suggestion:

```sh
# load a profile from local disk
nucamino --profile /path/to/a/local/profile.yml [other options]

# load a built-in profile, by adding an initial "@" to indicate it
nucamino --profile @hiv1b [other options]
```

Let me know what's in your mind. Thanks!

**Comment by neganp** [comment]
I think I can see how that would work. The profile for a strain would contain:

- reference gene sequences
- positional indel scores
- penalties for gaps, indels, and stop codons
- maybe metadata about the virus (e.g. Genebank accession numbers for reference sequences)

The built-in profiles could be written in the same format and embedded in the compiled program.

If that sounds about right, I could work on making those changes after I've added HCV support (that way we have two example profiles to work from instead of just one).

**Comment by philiptzou** [comment]
You are totally right and it will be a major release of NucAmino.

**Comment by philiptzou** [comment]
@neganp Thank you in advance for the contributions you did and will do to this project. Let me know when you finished :)

**Comment by neganp** [comment]
You're welcome; I'm happy to be able to contribute :smile: 

The email is because I fat-fingered a git push and pushed to my `master` instead of my feature branch. This PR is ready to merge; I've got another one in the works for adding HCV support. It's nearly ready, I'm just validating that it can catch the InDels we're interested in.

**Comment by philiptzou** [comment]
@neganp I have merged this pull request.

However, I'll hold for release until we finished the profile feature.

**Comment by neganp** [comment]
Thanks! I'm happy to wait for a release. I'll probably have two more PRs: one for HCV1A support and one to add position-specific indel scores.

**Pull request merged**
